import mongoose from "mongoose";

const sessionSchema = new mongoose.Schema(
  {
    // Session identification
    sessionId: {
      type: String,
      required: false, // Auto-generated by pre-save hook
    },

    // User reference
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    // Language and phrase
    language: {
      type: String,
      required: true,
      default: "en-US",
    },

    targetPhrase: {
      type: String,
      required: true,
    },

    transcribedText: {
      type: String,
      default: "",
    },

    // Core metrics (0-100)
    accuracy: {
      type: Number,
      required: true,
      min: 0,
      max: 100,
      default: 0,
    },

    fluency: {
      type: Number,
      required: true,
      min: 0,
      max: 100,
      default: 0,
    },

    prosody: {
      type: Number,
      required: true,
      min: 0,
      max: 100,
      default: 0,
    },

    // Overall score
    finalScore: {
      type: Number,
      required: true,
      min: 0,
      max: 100,
      default: 0,
    },

    // Words per minute
    wpm: {
      type: Number,
      default: 0,
    },

    // Audio duration in seconds
    duration: {
      type: Number,
      default: 0,
    },

    // Feedback color (green, yellow, red)
    color: {
      type: String,
      enum: ["green", "yellow", "red"],
      default: "red",
    },

    // Feedback message
    feedback: {
      type: String,
      default: "",
    },
  },
  {
    timestamps: true, // Automatically adds createdAt and updatedAt
  }
);

// Index for faster queries
sessionSchema.index({ userId: 1, createdAt: -1 });
sessionSchema.index({ sessionId: 1 }, { unique: true });

// Generate unique session ID before saving
sessionSchema.pre("save", function () {
  if (!this.sessionId) {
    this.sessionId = `session_${Date.now()}_${Math.random()
      .toString(36)
      .substr(2, 9)}`;
  }
});

// Instance method to get public data
sessionSchema.methods.toPublicProfile = function () {
  return {
    id: this._id,
    sessionId: this.sessionId,
    userId: this.userId,
    language: this.language,
    targetPhrase: this.targetPhrase,
    transcribedText: this.transcribedText,
    accuracy: this.accuracy,
    fluency: this.fluency,
    prosody: this.prosody,
    finalScore: this.finalScore,
    wpm: this.wpm,
    duration: this.duration,
    color: this.color,
    feedback: this.feedback,
    createdAt: this.createdAt,
    updatedAt: this.updatedAt,
  };
};

const Session = mongoose.model("Session", sessionSchema);

export default Session;
